controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    joint_position_example_controller:
      type: franka_example_controllers/JointPositionExampleController

    joint_velocity_example_controller:
      type: franka_example_controllers/JointVelocityExampleController

    joint_impedance_example_controller:
      type: franka_example_controllers/JointImpedanceExampleController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController
    
    gripper_controller:
      type: position_controllers/GripperActionController

joint_position_example_controller:
  ros__parameters:
    gazebo: true

joint_velocity_example_controller:
  ros__parameters:
    gazebo: true
  
joint_impedance_example_controller:
  ros__parameters:
    k_gains:
      - 24.0
      - 24.0
      - 24.0
      - 24.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5

arm_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    use_sim_time: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      fr3_joint1: { trajectory: 0.1, goal: 0.1 }
      fr3_joint2: { trajectory: 0.1, goal: 0.1 }
      fr3_joint3: { trajectory: 0.1, goal: 0.1 }
      fr3_joint4: { trajectory: 0.1, goal: 0.1 }
      fr3_joint5: { trajectory: 0.1, goal: 0.1 }
      fr3_joint6: { trajectory: 0.1, goal: 0.1 }
      fr3_joint7: { trajectory: 0.1, goal: 0.1 }

joint_group_position_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    interface_name: position
    use_sim_time: true

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
      - fr3_finger_joint1
      - fr3_finger_joint2

gripper_controller:
  ros__parameters:
    joint: fr3_finger_joint1
    command_interface: position
    use_sim_time: true